.TH get 1 "23 Nov 2025" "get 0.5.0" "User Commands"
.SH NAME
get \- package manager for GitHub releases
.SH SYNOPSIS
.B get
\- install|list|remove|update|upgrade [options]
.SH DESCRIPTION
get is a small CLI tool to install and manage binaries published as GitHub releases.
.SH AUTHOR
tranquil <tranquil@example.com>
